/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/login": {
    /** Request user to login */
    post: operations["userLogin"];
  };
}

export interface components {
  schemas: {
    /**
     * Error
     * @description Represents error details.
     * Common error responses are represented in example.
     */
    Error: {
      /**
       * @description Error code
       * The code must be machine friendly since it is intended to be used to distinct errors and written in PascalCase.
       */
      code: string;
      /** @description Additional useful informations for debbuging */
      details?: {
        message?: string;
      }[];
    };
  };
  responses: {};
}

export interface operations {
  /** Request user to login */
  userLogin: {
    responses: {
      /** Login success */
      200: unknown;
      /** Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** Login failed by incorrect login credentials */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
    /** An Login ID and Password pair of user to login. */
    requestBody: {
      content: {
        "application/json": {
          /**
           * Format: login-id
           * @description User Login ID
           * @example myLoginId
           */
          loginId: string;
          /**
           * Format: password
           * @description User Password
           * @example p@SSw0rd
           */
          password: string;
        };
      };
    };
  };
}

export interface external {}
